-- 코드를 입력하세요
SELECT DISTINCT f.FLAVOR FROM ICECREAM_INFO as i JOIN FIRST_HALF as f ON f.FLAVOR = i.FLAVOR WHERE i.INGREDIENT_TYPE = 'fruit_based' AND f.TOTAL_ORDER > 3000 ORDER BY f.TOTAL_ORDER DESC;

/*SELECT FLAVOR FROM ICECREAM_INFO WHERE INGREDIENT_TYPE = 'fruit_based';*/

/*SELECT FLAVOR FROM FIRST_HALF WHERE TOTAL_ORDER > 3000;*/


