-- 코드를 입력하세요
SELECT o.ANIMAL_ID, o.ANIMAL_TYPE, o.NAME
FROM ANIMAL_INS i RIGHT OUTER JOIN ANIMAL_OUTS o ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE LEFT(i.SEX_UPON_INTAKE, 6) = 'Intact' AND LEFT(o.SEX_UPON_OUTCOME, 6) != 'Intact';